[features]
seeds = false
[programs.localnet]
solana_twitter = "8nvyv1H8ArC62agd9xQeQbWuNaErUmiUUz9C26ydwzRH"

[programs.devnet]
solana_twitter = "8nvyv1H8ArC62agd9xQeQbWuNaErUmiUUz9C26ydwzRH"

[programs.testnet]
solana_twitter = "8nvyv1H8ArC62agd9xQeQbWuNaErUmiUUz9C26ydwzRH"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/home/jaylee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"