[features]
seeds = false
[programs.localnet]
solana_nft_collaterized_loans = "255yi18db8EQa9DgWQ8xmiVxBhE37ViN75ie2m64p4Wg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
