[features]
seeds = false
[programs.localnet]
custom_staking = "8VGWpYop4igS2dCmXr4vyQnJkhk5UUZjEArgj9JPAYk3"
[programs.mainnet]
custom_staking = "8VGWpYop4igS2dCmXr4vyQnJkhk5UUZjEArgj9JPAYk3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
